apiVersion: v1
kind: Service
metadata:
  name: marketplace-gateway
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 9000
    nodePort: 30900
  selector:
    app: marketplace-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-gateway
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: marketplace-gateway
  template:
    metadata:
      labels:
        app: marketplace-gateway
    spec:
      containers:
      - name: marketplace-gateway
        image: itssena/marketplace-gateway:latest
        ports:
        - containerPort: 9000
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: EUREKA_URL
          value: "http://eureka/eureka"
        - name: LOGSTASH_HOST
          value: "logstash"
        - name: LOGSTASH_PORT
          value: "5000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
