apiVersion: v1
kind: Service
metadata:
  name: produk
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8081
    nodePort: 30092
  selector:
    app: produk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: produk
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: produk
  template:
    metadata:
      labels:
        app: produk
    spec:
      containers:
      - name: produk
        image: itssena/produk:latest
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: EUREKA_URL
          value: "http://eureka/eureka"
        - name: CQRS_SERVICE_URL
          value: "http://cqrs"
        - name: LOGSTASH_HOST
          value: "logstash"
        - name: LOGSTASH_PORT
          value: "5000"
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq"
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: "itssena"
        - name: SPRING_RABBITMQ_PASSWORD
          value: "070078"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
